### PR TITLE
Simplified selection logic

### LINKED ISSUE #9: Add better selection logic
Current logic uses too many calls to an external library, and also requires a loop. 
A more pythonic approach would be to shuffle the list and then simply use a list slice to select the first N elements.

### PR DESCRIPTION
**Pull request by aperullo**
fixes #9 
Easier to understand and also faster!
Also added .gitignore.

@pvargas @rfding @mdang8 @josephthweatt

### CODE REVIEW

**Review by mdang8 — COMMENTED** [review]
Can you reference an issue in the PR?

**Review by rfding — APPROVED** [review]

**Comment by aperullo** [comment]
> Can you reference an issue in the PR?

**Review by mdang8 — CHANGES_REQUESTED** [review]
Needs a reference to an issue.

**Comment by mdang8** [comment]
> > Can you reference an issue in the PR?
> 
> [FOOD-3] Matt is a stickler.

This is not a valid reference to an issue. Here is a link to [instructions on how to create GitHub issues](https://help.github.com/articles/creating-an-issue/) and instructions on [how to link them to your pull requests](https://help.github.com/articles/autolinked-references-and-urls/).

**Comment by aperullo** [comment]
Edited

**Review by pvargas — APPROVED** [review]

**Review by mdang8 — APPROVED** [review]

**Pull request merged**
